# Generated by Django 4.1.6 on 2023-04-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=255)),
                ('port', models.IntegerField(default=29999)),
            ],
        ),
    ]
