# Generated by Django 4.1.6 on 2023-04-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Robot',
        ),
    ]
